# tell travis to copy the docker
sudo: required

services:
  - docker

before_install:
  - docker build -t mallabishal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mallabishal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-338257658451"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  on
    branch: master