# tell travis to copy the docker
sudo: required

services:
  - docker

before_install:
  - docker build -t mallabishal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mallabishal/docker-react npm run test